src/Valouleloup/IssueBundle/Entity/Theme.php
<?php

namespace Valouleloup\IssueBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;

class Theme
{
    /**
     * @var int
     */
    private $id;

    /**
     * @var string
     */
    private $label;

    /**
     * @var Collection
     */
    private $issues;

    /**
     * @var \DateTime
     */
    private $createdAt;

    /**
     * @var \DateTime
     */
    private $updatedAt;

    public function __construct()
    {
        $this->issues = new ArrayCollection();
    }

    /**
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return string
     */
    public function getLabel()
    {
        return $this->label;
    }

    /**
     * @param string $label
     */
    public function setLabel($label)
    {
        $this->label = $label;
    }

    /**
     * @return Collection
     */
    public function getIssues()
    {
        return $this->issues;
    }

    /**
     * @param Issue $issue
     */
    public function setIssues($issue)
    {
        $this->issues->add($issue);

        $issue->setTheme($this);
    }

    /**
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * @param \DateTime $createdAt
     */
    public function setCreatedAt($createdAt)
    {
        $this->createdAt = $createdAt;
    }

    /**
     * @return \DateTime
     */
    public function getUpdatedAt()
    {
        return $this->updatedAt;
    }

    /**
     * @param \DateTime $updatedAt
     */
    public function setUpdatedAt($updatedAt)
    {
        $this->updatedAt = $updatedAt;
    }

    /**
     * @return int
     */
    public function getNbPosts()
    {
        $result = 0;

        foreach ($this->issues as $issue) {
            $result += $issue->getNbPosts();
        }

        return $result;
    }
}

src/Valouleloup/IssueBundle/Form/ThemeType.php
<?php

namespace Valouleloup\IssueBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Valouleloup\IssueBundle\Entity\Theme;

class ThemeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('label', TextType::class)
            ->add('submit', SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Theme::class,
        ]);
    }

    public function getBlockPrefix()
    {
        return 'form_theme';
    }
}

src/Valouleloup/IssueBundle/Controller/ThemeController.php
<?php

namespace Valouleloup\IssueBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Valouleloup\IssueBundle\Entity\Theme;
use Valouleloup\IssueBundle\Form\ThemeType;

class ThemeController extends Controller
{
    /**
     * @return Response
     */
    public function newAction()
    {
        $theme = new Theme();

        $form = $this->createForm(
            ThemeType::class,
            $theme,
            [
                'action' => $this->generateUrl('create_theme'),
                'method' => 'POST',
            ]
        );

        return $this->render('@ValouleloupIssue/Theme/add.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    /**
     * @param Request $request
     *
     * @return Response
     */
    public function createAction(Request $request)
    {
        $theme = new Theme();

        $form = $this->createForm(ThemeType::class, $theme);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($theme);
            $em->flush();

            $this->addFlash('success', 'flash.theme.create');

            return $this->redirectToRoute('list_themes');
        }

        return $this->render('@ValouleloupIssue/Theme/add.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    /**
     * @return Response
     */
    public function listAction()
    {
        $repo   = $this->getDoctrine()->getRepository('ValouleloupIssueBundle:Theme');
        $themes = $repo->findAll();

        return $this->render('@ValouleloupIssue/Theme/list.html.twig', [
            'themes' => $themes,
        ]);
    }
}

src/Valouleloup/IssueBundle/Resources/views/Theme/add.html.twig
{% extends '@ValouleloupIssue/Theme/base_theme.html.twig' %}

{% block body %}
    <div class="row">
        <div class="panel panel-default send-theme" id="send-theme">

            <div class="panel-heading">New Theme</div>
            <div class="panel-body">
                <div class="form">
                    {{ form_start(form) }}
                    {{ form_widget(form.submit, {'attr': {'class': 'btn btn-success btn-submit pull-right'}, 'label' : 'Add Theme'}) }}
                    {{ form_end(form) }}
                </div>
            </div>

        </div>
    </div>
{% endblock %}

src/Valouleloup/IssueBundle/Resources/views/Theme/base_theme.html.twig
{% extends '@ValouleloupIssue/base.html.twig' %}

{% block current_top_navigation %}
    <h4><a>Home</a> / <a>Themes</a></h4>
{% endblock %}

{% block body_nav_themes %}
    <li class="active">
        <a href="{{ path('list_themes') }}">Themes {% block theme_list_badge %}{% endblock %}</a>
    </li>
{% endblock %}

src/Valouleloup/IssueBundle/Resources/views/Theme/list.html.twig
{% extends '@ValouleloupIssue/Theme/base_theme.html.twig' %}

{% block theme_list_badge %}
    <span class="badge">{{ themes|length }}</span>
{% endblock %}

{% block body %}
    <div class="row">
        <a class="btn btn-success pull-right" href="{{ path('add_theme') }}">Add Theme</a>
    </div>

    <div class="row">
        <div class="panel panel-default list-elements">

            <div class="panel-heading"> List themes </div>
            <div class="panel-body">
                {% for theme in themes %}
                    <div class="col-sm-12 single-element">
                        <div class="col-sm-10 title">
                            <a href="{{ path('list_issue_theme', {'id': theme.id}) }}">{{ theme.label }}</a>
                        </div>
                        <div class="col-sm-2 infos info-comments text-right">
                            {{ theme.nbPosts }} comments
                        </div>
                    </div>
                {% endfor %}
            </div>

        </div>
    </div>
{% endblock %}